"""Generate csrc/model_constants.h from the Python model definition.

The C program needs every tunable, ladder and lookup table that `hve/model.py`,
`hve/mix.py` and `hve/video.py` define. Retyping them into C would be the worst
kind of duplication: a single wrong digit does not fail to compile, it silently
produces a different model, and the only symptom is a slightly worse ratio.

So they are generated instead, and `tests/test_generated_constants.py` fails if
the checked-in header is stale. Run this after changing any constant:

    .venv/bin/python tools/gen_model_constants.py

The generated file is committed so that building the binary needs only a C
compiler, with no Python step in the way.
"""

import inspect
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from hve import image, mix, model, rc, video  # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "csrc", "model_constants.h")


def _mv_penalty():
    """The flat price choose_modes charges for sending a vector.

    It is a default argument rather than a module constant, so read it out of
    the signature instead of copying the number - a copy here is exactly the
    kind of silent divergence this generator exists to prevent.
    """
    return inspect.signature(video.choose_modes).parameters["mv_penalty"].default


def _rows(values, per_line, fmt="%d"):
    out = []
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        out.append("    " + " ".join(fmt % v + "," for v in chunk))
    return "\n".join(out)


def _array(ctype, name, values, per_line=16):
    return ("static const %s %s[%d] = {\n%s\n};\n"
            % (ctype, name, len(values), _rows(values, per_line)))


def generate():
    bank = model.new_model()
    lines = []
    add = lines.append

    add("/* GENERATED by tools/gen_model_constants.py - do not edit.")
    add(" *")
    add(" * Every value here comes from hve/model.py, hve/mix.py, hve/rc.py or")
    add(" * hve/video.py. Change them there and re-run the generator; editing this")
    add(" * file directly makes the C program disagree with the reference and the")
    add(" * only symptom is a worse compression ratio.")
    add(" */")
    add("")
    add("#ifndef HVE_MODEL_CONSTANTS_H")
    add("#define HVE_MODEL_CONSTANTS_H")
    add("")
    add("#include <stdint.h>")
    add("")

    add("/* --- container --- */")
    add('#define HVI_MAGIC "%s"' % image.MAGIC.decode("ascii"))
    add('#define HVV_MAGIC "%s"' % video.MAGIC.decode("ascii"))
    add("#define HVE_FLAG_RCT %d" % image.FLAG_RCT)
    add("")

    add("/* --- video --- */")
    for name, value in (("HVE_BLOCK", video.BLOCK), ("HVE_SEARCH", video.SEARCH),
                        ("HVE_MV_MAX", video.MV_MAX),
                        ("HVE_HALF_PEL_BIAS", video.HALF_PEL_BIAS),
                        ("HVE_PYRAMID_MIN_PIXELS", video.PYRAMID_MIN_PIXELS),
                        ("HVE_PYRAMID_LEVELS", video.PYRAMID_LEVELS),
                        ("HVE_REFINE_RADIUS", video.REFINE_RADIUS),
                        ("HVE_MV_PENALTY", _mv_penalty())):
        add("#define %s %d" % (name, value))
    add("")

    add("/* --- model shape --- */")
    for name, value in (("HVE_KINDS", model.KINDS), ("HVE_NACT", model.NACT),
                        ("HVE_NERR", model.NERR), ("HVE_NLUM", model.NLUM),
                        ("HVE_NSIDE", model.NSIDE), ("HVE_NDIFF", model.NDIFF),
                        ("HVE_NMATCH", model.NMATCH),
                        ("HVE_MAX_NB", model.MAX_NB),
                        ("HVE_NMEXP", model.NMEXP),
                        ("HVE_NMSIGN", model.NMSIGN),
                        ("HVE_NCONF", model.NCONF), ("HVE_NADJ", model.NADJ),
                        ("HVE_ZERO_EXPERTS", model.ZERO_EXPERTS),
                        ("HVE_NB_EXPERTS", 3),
                        ("HVE_MATCH_HASH_MASK", model.MATCH_HASH_MASK),
                        ("HVE_PROB_INIT", rc.PROB_INIT),
                        ("HVE_WEIGHT_ONE", mix.WEIGHT_ONE),
                        ("HVE_APM_BUCKETS", mix.APM.BUCKETS)):
        add("#define %s %d" % (name, value))
    add("")

    add("/* --- bank sizes, in the order hve/native.py binds them --- */")
    for cname, key in (("HVE_N_ZERO", "zero"), ("HVE_N_DIR", "zero_dir"),
                       ("HVE_N_DIFF", "zero_diff"), ("HVE_N_MATCH", "zero_match"),
                       ("HVE_N_SIGN", "sign"), ("HVE_N_NB", "nb"),
                       ("HVE_N_NBM", "nb_match"), ("HVE_N_MANT", "mant"),
                       ("HVE_N_CONF", "zero_conf"), ("HVE_N_NBC", "nb_conf")):
        add("#define %s %d" % (cname, len(bank[key])))
    add("#define HVE_N_MIXW %d" % len(bank["zero_mix"].weights))
    add("#define HVE_N_NBMIXW %d" % len(bank["nb_mix"].weights))
    add("#define HVE_N_LMSW %d" % len(bank["lms"]))
    add("#define HVE_N_APM0 %d" % len(bank["zero_apm"].table))
    add("#define HVE_N_APM1 %d" % len(bank["nb_apm"].table))
    add("#define HVE_N_APM2 %d" % len(bank["zero_apm2"].table))
    add("")

    add("/* --- tunables, indexed by the enum in csrc/hve.h --- */")
    add(_array("int64_t", "HVE_PARAMS", [int(v) for v in model.coder_params()], 8))

    add("/* --- context ladders --- */")
    for name, ladder in (("ACT", model.ACT_LADDER), ("ERR", model.ERR_LADDER),
                         ("LUM", model.LUMA_LADDER), ("SIDE", model.SIDE_LADDER),
                         ("DIFF", model.DIFF_LADDER), ("MEXP", model.MEXP_LADDER),
                         ("CONF", model.CONF_LADDER), ("ADJ", model.ADJ_LADDER)):
        add(_array("int64_t", "HVE_LADDER_" + name, list(ladder), 12))

    add("/* --- APM initial row; every context starts from the same identity map --- */")
    add(_array("int64_t", "HVE_APM_INIT",
               list(bank["zero_apm"].table[:mix.APM.BUCKETS]), 8))

    add("/* --- logistic mixing tables (mix.STRETCH / mix.SQUASH) --- */")
    add(_array("int16_t", "HVE_STRETCH", list(mix.STRETCH), 20))
    add(_array("int16_t", "HVE_SQUASH", list(mix.SQUASH), 20))

    add("/* --- motion search cost proxy (video._COST_BYTE) --- */")
    add(_array("int32_t", "HVE_COST_BYTE", [int(v) for v in video._COST_BYTE], 20))

    add("#endif /* HVE_MODEL_CONSTANTS_H */")
    return "\n".join(lines) + "\n"


def main():
    text = generate()
    existing = None
    if os.path.exists(OUT):
        with open(OUT) as fh:
            existing = fh.read()
    if existing == text:
        print("csrc/model_constants.h already up to date")
        return 0
    with open(OUT, "w") as fh:
        fh.write(text)
    print("wrote csrc/model_constants.h (%d bytes)" % len(text))
    return 0


if __name__ == "__main__":
    sys.exit(main())
